/* generic tables definition for project : BIGID */
SET FOREIGN_KEY_CHECKS = 0;

/* table to save user info + credentials for login */
DROP TABLE IF EXISTS USER;
CREATE TABLE USER (
 ID BIGINT(20) AUTO_INCREMENT NOT NULL PRIMARY KEY,
 USERNAME VARCHAR(32) NOT NULL UNIQUE KEY,
 PASSWORD VARCHAR(100) NOT NULL,
 EMAIL VARCHAR(50) DEFAULT NULL,
 AVATAR_IMG_PATH VARCHAR(300) DEFAULT NULL,
 DOB DATE DEFAULT NULL,
 CITY VARCHAR(20) DEFAULT NULL,
 LONGITUDE DECIMAL(9,6) DEFAULT NULL,
 LATITUDE DECIMAL(9,6) DEFAULT NULL,
 -- VOTE_DAILY_LIMIT TINYINT UNSIGNED DEFAULT 0,
 USER_TYPE ENUM('USER','ADMIN') DEFAULT 'USER',
 CREATION_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 LAST_MODIFIED_TIMESTAMP timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 LAST_LOGIN_TSTMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP 
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS ROLE_MASTER;
CREATE TABLE ROLE_MASTER (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ROLE_NAME VARCHAR(255) DEFAULT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS USER_ROLE_REL;
CREATE TABLE USER_ROLE_REL (
  USER_ID BIGINT(20) NOT NULL,
  ROLE_ID BIGINT(20) NOT NULL,
  PRIMARY KEY (USER_ID,ROLE_ID),
  CONSTRAINT USER_ID_FK FOREIGN KEY (ROLE_ID) REFERENCES ROLE_MASTER (ID),
  CONSTRAINT ROLE_MASTER_ID_FK FOREIGN KEY (USER_ID) REFERENCES USER (ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

/* table to record user and whom he/she is following */
DROP TABLE IF EXISTS USER_FOLLOWER_REL;
CREATE TABLE USER_FOLLOWER_REL (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  FOLLOWED_BY BIGINT(20) NOT NULL,
  FOLLOWING_TO BIGINT(20) NOT NULL,
  SINCE_FOLLOWING TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  IS_NOTIFICATION_ON BOOLEAN DEFAULT FALSE,
  CONSTRAINT FOLLOWED_BY_FK FOREIGN KEY (FOLLOWED_BY) REFERENCES USER (ID),
  CONSTRAINT FOLLOWING_TO_FK FOREIGN KEY (FOLLOWING_TO) REFERENCES USER (ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

/* table to save user post, be it event,visual,question,comments,general or link */
DROP TABLE IF EXISTS USER_POST;
CREATE TABLE USER_POST (
  ID BIGINT(20) AUTO_INCREMENT NOT NULL PRIMARY KEY,
  TITLE VARCHAR(50) DEFAULT NULL,  /* FOR EVENT (DATE +LOCATION), QUESTION (?), VISUAL (NULL) AND LINK( URL) CAN BE SAVED IN TITLE */
  BODY VARCHAR(300) DEFAULT NULL,      /* FOR EVENT (DESCRIPTION), QUESTION (THOUGHTS), VISUAL (CAPTION) AND LINK( DESCRIPTION) CAN BE SAVED IN TITLE */
  TAGS VARCHAR (150) DEFAULT NULL,
  TYPE ENUM('GENERAL','EVENT','QUESTION','VISUAL','LINK','COMMENT'),
  CATEGORY ENUM('FUNNY','CASUAL','SERIOUS','SMALL', 'PROVOCATIVE'),
  LONGITUDE DECIMAL(9,6) DEFAULT NULL,
  LATITUDE DECIMAL(9,6) DEFAULT NULL,
  IMG_PATH VARCHAR(300) DEFAULT NULL,
  PARENT_POST_ID BIGINT(20) DEFAULT NULL,
  CREATED_BY BIGINT(20) NOT NULL,
  CREATION_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  LAST_MODIFIED_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  TOTAL_VOTES_CNT INT SIGNED DEFAULT 0,
  TOTAL_COMMENTS_CNT INT UNSIGNED DEFAULT 0,
  IS_ANONYMOUS BOOLEAN NULL DEFAULT FALSE,
  CONSTRAINT USER_POST_CREATED_BY_FK FOREIGN KEY (CREATED_BY) REFERENCES USER (ID),
  CONSTRAINT USER_POST_PARENT_POST_ID_FK FOREIGN KEY (PARENT_POST_ID) REFERENCES USER_POST (ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS USER_POST_MISC;
CREATE TABLE USER_POST_MISC (
  POST_ID BIGINT(20) NOT NULL,
  NSFW BOOLEAN NOT NULL DEFAULT FALSE,
  TO_FIELD VARCHAR(30) DEFAULT NULL,
  FROM_FIELD VARCHAR(30) DEFAULT NULL, 
  CONSTRAINT USER_POST_MISC_POST_ID_FK FOREIGN KEY (POST_ID) REFERENCES USER_POST (ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
  
DROP TABLE IF EXISTS USER_POST_VOTE_DETAIL;
CREATE TABLE USER_POST_VOTE_DETAIL (
  ID BIGINT(20) AUTO_INCREMENT NOT NULL PRIMARY KEY,
  POST_ID BIGINT(20) NOT NULL,
  USER_ID BIGINT(20) NOT NULL,
  VOTE_TYPE ENUM('UP','DOWN') DEFAULT NULL,
  CREATION_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT USER_POST_VOTE_DETAIL_POST_ID_FK FOREIGN KEY (POST_ID) REFERENCES USER_POST (ID),
  CONSTRAINT USER_POST_VOTE_DETAIL_USER_ID_FK FOREIGN KEY (USER_ID) REFERENCES USER (ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;


/* CONDITIONAL TABLE, IF USER_POST IS NOT PREFER TO SAVE ALL SUB_TYPE INFOS */
/*===========================STARTS HERE ===============================*/
DROP TABLE IF EXISTS USER_EVENT_POST;
CREATE TABLE USER_EVENT_POST
(
POST_ID BIGINT(20) NOT NULL,
EVENT_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  /* Seems USER_POST can save event date in title and description in body field */
DESCRIPTION VARCHAR(1000) NOT NULL,
PLACE VARCHAR(25) NOT NULL, 
CONSTRAINT USER_EVENT_POST_POST_ID_FK FOREIGN KEY (POST_ID) REFERENCES USER_POST (ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS USER_QUESTION_POST;
CREATE TABLE USER_QUESTION_POST
(
POST_ID BIGINT(20) NOT NULL,
QUESTION TIMESTAMP DEFAULT CURRENT_TIMESTAMP, /* IF USER_POST CAN SAVE QUESTION IN TITLE AND THOUGHTS IN DESCRITPION THEN THIS SUB TABLE IS NOT REQUIRED*/
THOUGHTS VARCHAR(1000) NOT NULL,
CONSTRAINT USER_QUESTION_POST_ID_FK FOREIGN KEY (POST_ID) REFERENCES USER_POST (ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS USER_VISUAL_POST;
CREATE TABLE USER_VISUAL_POST
(
POST_ID BIGINT(20) NOT NULL,
CAPTION VARCHAR(200) NOT NULL,
CONSTRAINT USER_VISUAL_POST_ID_FK FOREIGN KEY (POST_ID) REFERENCES USER_POST (ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS USER_LINK_POST;
CREATE TABLE USER_LINK_POST
(
POST_ID BIGINT(20) NOT NULL,
LINK_URL VARCHAR(100) DEFAULT NULL,
DESCRIPTION VARCHAR(200) NOT NULL,
CONSTRAINT USER_LINK_POST_ID_FK FOREIGN KEY (POST_ID) REFERENCES USER_POST (ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

/*===========================ENDS HERE ===============================*/

SET FOREIGN_KEY_CHECKS = 1;