
INSERT INTO USER_POST(ID,TITLE,BODY,TAGS,TYPE,CATEGORY,LONGITUDE,LATITUDE,IMG_PATH,PARENT_POST_ID,CREATED_BY,CREATION_TIMESTAMP,LAST_MODIFIED_TIMESTAMP,TOTAL_VOTES_CNT,TOTAL_COMMENTS_CNT,IS_ANONYMOUS) values(null,'General post from India-mumbai',' This is the first general post on bigid', 'general,blog', 'GENERAL','FUNNY',19.075984,72.877656,'/img/pp/aa/tt',null,1,now(),now(),0,0,false);
INSERT INTO USER_POST(ID,TITLE,BODY,TAGS,TYPE,CATEGORY,LONGITUDE,LATITUDE,IMG_PATH,PARENT_POST_ID,CREATED_BY,CREATION_TIMESTAMP,LAST_MODIFIED_TIMESTAMP,TOTAL_VOTES_CNT,TOTAL_COMMENTS_CNT,IS_ANONYMOUS) values(null,'General post from Mountain View, CA 94043, USA','General post from Mountain View, CA 94043, USA', 'general,blog,USA', 'GENERAL','SERIOUS', 37.393020,-122.077757,'/img/pp/aa/tt',null,1,now(),now(),0,0,false);

INSERT INTO USER_POST(ID,TITLE,BODY,TAGS,TYPE,CATEGORY,LONGITUDE,LATITUDE,IMG_PATH,PARENT_POST_ID,CREATED_BY,CREATION_TIMESTAMP,LAST_MODIFIED_TIMESTAMP,TOTAL_VOTES_CNT,TOTAL_COMMENTS_CNT,IS_ANONYMOUS) values(null,'Event from london englandS','London is easily the best city on the planet. It beats New York hands down, every single time. The History of Britain is so diverse and stretches much further back than that of the US, and much of the fascinating culture of this is located in London. London\'s Impressive architecture includes Buckingham Palace', 'event,gathering', 'EVENT','FUNNY', 51.507351,-0.127758,'/img/pp/aa/tt',null,1,now(),now(),0,0,false);

INSERT INTO USER_POST(ID,TITLE,BODY,TAGS,TYPE,CATEGORY,LONGITUDE,LATITUDE,IMG_PATH,PARENT_POST_ID,CREATED_BY,CREATION_TIMESTAMP,LAST_MODIFIED_TIMESTAMP,TOTAL_VOTES_CNT,TOTAL_COMMENTS_CNT,IS_ANONYMOUS) values(null,'General post from New York City, U.S.A','The museum of natural history is the best site I\'ve seen in this city. I could have voted for both New York and London. I think London and New York are both the same. I\'ve visited them both, and I can tell they both are very nice cities', 'general,blog', 'GENERAL','FUNNY',40.712784,-74.005941,'/img/pp/aa/tt',null,1,now(),now(),0,0,false);

INSERT INTO USER_POST(ID,TITLE,BODY,TAGS,TYPE,CATEGORY,LONGITUDE,LATITUDE,IMG_PATH,PARENT_POST_ID,CREATED_BY,CREATION_TIMESTAMP,LAST_MODIFIED_TIMESTAMP,TOTAL_VOTES_CNT,TOTAL_COMMENTS_CNT,IS_ANONYMOUS) values(null,'Whats so special about Paris ?','Lots of my friend always talk about paris, France. But not sure what is so special in paris city ?', 'general,question,query', 'QUESTION','SMALL',48.856614,2.352222,'/img/pp/aa/tt',null,1,now(),now(),0,0,false);

INSERT INTO USER_POST(ID,TITLE,BODY,TAGS,TYPE,CATEGORY,LONGITUDE,LATITUDE,IMG_PATH,PARENT_POST_ID,CREATED_BY,CREATION_TIMESTAMP,LAST_MODIFIED_TIMESTAMP,TOTAL_VOTES_CNT,TOTAL_COMMENTS_CNT,IS_ANONYMOUS) values(null,'Visual from Tokyo, Japan',' This visual is from Japan.', 'general,blog', 'VISUAL','CASUAL', 35.689487,139.691706,'/img/pp/aa/tt',null,1,now(),now(),0,0,false);

INSERT INTO USER_POST(ID,TITLE,BODY,TAGS,TYPE,CATEGORY,LONGITUDE,LATITUDE,IMG_PATH,PARENT_POST_ID,CREATED_BY,CREATION_TIMESTAMP,LAST_MODIFIED_TIMESTAMP,TOTAL_VOTES_CNT,TOTAL_COMMENTS_CNT,IS_ANONYMOUS) values(null,'https://en.wikipedia.org/wiki/Sydney ','Wikipedia on Sydney, Australia', 'link,picture', 'LINK','FUNNY', -33.868820,151.209296,'/img/pp/aa/tt',null,1,now(),now(),0,0,false);

INSERT INTO USER_POST(ID,TITLE,BODY,TAGS,TYPE,CATEGORY,LONGITUDE,LATITUDE,IMG_PATH,PARENT_POST_ID,CREATED_BY,CREATION_TIMESTAMP,LAST_MODIFIED_TIMESTAMP,TOTAL_VOTES_CNT,TOTAL_COMMENTS_CNT,IS_ANONYMOUS) values(null,'Event from Dubai, U.A.E.','Meet up in Burj Khalifa', 'general,blog', 'EVENT','FUNNY',25.204849,55.270783,'/img/pp/aa/tt',null,1,now(),now(),0,0,TRUE);
INSERT INTO USER_POST_MISC(POST_ID ,NSFW ,TO_FIELD ,FROM_FIELD) values(LAST_INSERT_ID(),TRUE,'SMITH','JOHN');

INSERT INTO USER_POST(ID,TITLE,BODY,TAGS,TYPE,CATEGORY,LONGITUDE,LATITUDE,IMG_PATH,PARENT_POST_ID,CREATED_BY,CREATION_TIMESTAMP,LAST_MODIFIED_TIMESTAMP,TOTAL_VOTES_CNT,TOTAL_COMMENTS_CNT,IS_ANONYMOUS) values(null,'Google developer conference at Bangalore, India','google developer conference for indian', 'event,blog', 'EVENT','SERIOUS', 12.971599,77.594563,'/img/pp/aa/tt',null,1,now(),now(),0,0,true);
INSERT INTO USER_POST_MISC(POST_ID ,NSFW ,TO_FIELD ,FROM_FIELD) values(LAST_INSERT_ID(),TRUE,'ALICE','BOB');


INSERT INTO USER_POST(ID,TITLE,BODY,TAGS,TYPE,CATEGORY,LONGITUDE,LATITUDE,IMG_PATH,PARENT_POST_ID,CREATED_BY,CREATION_TIMESTAMP,LAST_MODIFIED_TIMESTAMP,TOTAL_VOTES_CNT,TOTAL_COMMENTS_CNT,IS_ANONYMOUS) values(null,'How google maps works? By Smith -Chicago, U.S.A.','google maps', 'question,google-map,query', 'QUESTION','PROVOCATIVE', 41.878114,-87.629798,'/img/pp/aa/tt',null,1,now(),now(),0,0,false);